const data = {
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirts',
            category:'Shirts',
            image:'/images/p1.jpg',
            price:120,
            brand:'Nike',
            ranking:4.5,
            numReviews:10,
            description:'High quality product',
        },
        {
            _id:'2',
            name:'Adidas Fit Shirts',
            category:'Shirts',
            image:'/images/p2.jpeg',
            price:100,
            brand:'Adidas',
            ranking:4.0,
            numReviews:10,
            description:'High quality product',
        },
        {
            _id:'3',
            name:'Lacoste Free Shirts',
            category:'Shirts',
            image:'/images/p3.jpeg',
            price:220,
            brand:'Lacoste',
            ranking:4.8,
            numReviews:17,
            description:'High quality product',
        },
        {
            _id:'5',
            name:'Nike Slim Jean',
            category:'Jeans',
            image:'/images/p5.jpg',
            price:300,
            brand:'Nike',
            ranking:3.5,
            numReviews:20,
            description:'High quality product',
        },
        {
            _id:'6',
            name:'  Adidas Shirts',
            category:'Shirts',
            image:'/images/p6.jpg',
            price:120,
            brand:'Adidas',
            ranking:4.5,
            numReviews:10,
            description:'High quality product',
        },
    ],
}

export default data;